# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
addons:
  apt:
    packages:
      - glpk
before_install:
    - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F6609E60DC62814E
  